Test multiple GHC versions on Travis
Travis configuration based on https://github.com/hvr/multi-ghc-travis.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,1 +1,44 @@
-language: haskell
+env:
+ - GHCVER=6.12.3
+ - GHCVER=7.0.1
+ - GHCVER=7.0.2
+ - GHCVER=7.0.3
+ - GHCVER=7.0.4
+ - GHCVER=7.2.1
+ - GHCVER=7.2.2
+ - GHCVER=7.4.1
+ - GHCVER=7.4.2
+ - GHCVER=7.6.1
+ - GHCVER=7.6.2
+ - GHCVER=7.6.3
+ - GHCVER=7.8.1
+ - GHCVER=7.8.2
+ - GHCVER=7.8.3
+
+before_install:
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER # see note about happy/alex
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH
+
+install:
+ - cabal update
+ - cabal install --only-dependencies --enable-tests
+
+script:
+ - cabal configure --enable-tests -v2
+ - cabal build
+ - hlint .
+ - cabal test
+ - cabal check
+ - cabal sdist
+
+# The following scriptlet checks that the resulting source distribution can be built & installed
+ - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
